// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-k98MGAyUvmxaH790a3L7QkkQdJs6URM',
    appId: '1:126978282132:web:6eaa266da236b3ed921a81',
    messagingSenderId: '126978282132',
    projectId: 'movies-route-project',
    authDomain: 'movies-route-project.firebaseapp.com',
    storageBucket: 'movies-route-project.firebasestorage.app',
    measurementId: 'G-GXSDR0YEL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MQWmTSGge7zvtDN7Ey8AVKjgLC3jQo4',
    appId: '1:126978282132:android:b37b222624d51dfc921a81',
    messagingSenderId: '126978282132',
    projectId: 'movies-route-project',
    storageBucket: 'movies-route-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHst3YvF0CV3cR7S8zOHC_ihHDuj_UXt0',
    appId: '1:126978282132:ios:71aa58beb3b91ab3921a81',
    messagingSenderId: '126978282132',
    projectId: 'movies-route-project',
    storageBucket: 'movies-route-project.firebasestorage.app',
    iosClientId: '126978282132-helcvggihspnu5utc1ou9e1npi39g1ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHst3YvF0CV3cR7S8zOHC_ihHDuj_UXt0',
    appId: '1:126978282132:ios:71aa58beb3b91ab3921a81',
    messagingSenderId: '126978282132',
    projectId: 'movies-route-project',
    storageBucket: 'movies-route-project.firebasestorage.app',
    iosClientId: '126978282132-helcvggihspnu5utc1ou9e1npi39g1ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-k98MGAyUvmxaH790a3L7QkkQdJs6URM',
    appId: '1:126978282132:web:a318a86e34d71c76921a81',
    messagingSenderId: '126978282132',
    projectId: 'movies-route-project',
    authDomain: 'movies-route-project.firebaseapp.com',
    storageBucket: 'movies-route-project.firebasestorage.app',
    measurementId: 'G-W92JQECDN5',
  );

}